export default {
  TrafficSignal: "Ampel",
  ModDefault: "Default",
  Vanilla: "Vanilla",
  SplitPhasing: "Aufgeteilte Phase",
  AdvancedSplitPhasing: "Erweiterte geteilte Phasen",
  ProtectedRightTurns: "Geschützes rechts abbiegen",
  ProtectedLeftTurns: "Geschützes links abbiegen",
  Options: "Optionen",
  ExclusivePedestrianPhase: "Exklusive Fußgängerphase",
  AlwaysGreenLeftTurns: "Links abbiegen immer erlaubt",
  AlwaysGreenRightTurns: "Rechts abbiegen immer erlaubt",
  LaneDirectionTool: "Fahrspurausrichtung (Experimentell)",
  Close: "Schließen",
  Open: "Öffnen",
  Reset: "Zurücksetzen",
  Save: "Speichern",
  PleaseSave: "Bitte speichere die Einstellungen, bevor du eine andere Kreuzung bearbeitest.",
  PleaseSelectJunction: "Bitte wähle eine Kreuzung aus",
  Left: "Links",
  Ahead: "Geradeaus",
  Right: "Rechts",
  UTurn: "U-Wende",
  GiveWayToOncomingVehicles: "Vorfahrt für entgegenkommende Fahrzeuge",
  CustomPedestrianDurationMultiplier: "Dauer der Fußgängerphase",
  CustomPedestrianDurationMultiplierSuffix: "x",
  AllowTurningOnRed: "Erlaube abbiegen bei Rot",
  CanaryBuildWarning: "Bitte beachte, dass du ein Canary-Build verwenden, das mit größerer Wahrscheinlichkeit spiel- oder speicherschädigende Bugs enthält und nur zum Testen gedacht ist. Verwenden Sie diesen Build NICHT für den normalen Spielbetrieb.",
  LdtMigrationNotice: "Lane Direction Tool has now been retired and succeeded by Traffic mod from krzychu124. Please install the Traffic mod, and it will automatically transfer your current lane settings to it. Click for more details (Open in a web browser).",
  LdtRetirementNotice: "Lane Direction Tool has now been retired and succeeded by Traffic mod from krzychu124. Thank you for using LDT."
};