export default {
  TrafficSignal: "Feux de circulations",
  Vanilla: "Vanilla",
  SplitPhasing: "Phase fractionnée",
  AdvancedSplitPhasing: "Feux fractionnés avancés",
  ProtectedRightTurns: "Virage à droite protégé",
  ProtectedLeftTurns: "Virage à gauche protégé",
  Options: "Options",
  ExclusivePedestrianPhase: "Feux exclusifs piétons",
  AlwaysGreenLeftTurns: "Tourner à gauche toujours vert",
  AlwaysGreenRightTurns: "Tourner à droite toujours vert",
  LaneDirectionTool: "Outil de direction par voie (expérimental)",
  Close: "Fermer",
  Open: "Ouvrir",
  Reset: "Réinitialiser",
  Save: "Sauvegarder",
  PleaseSave: "Veuillez enregistrer les modifications avant de sélectionner une autre intersection.",
  PleaseSelectJunction: "Veuillez sélectionner une intersection",
  Left: "Gauche",
  Ahead: "En face",
  Right: "Droite",
  UTurn: "Demi-tour",
  GiveWayToOncomingVehicles: "Céder le passage aux véhicules venant en sens inverse",
  CustomPedestrianDurationMultiplier: "Durée du feu exclusif aux piétons",
  CustomPedestrianDurationMultiplierSuffix: "x",
  AllowTurningOnRed: "Autoriser les virages lorsque le feu est rouge",
  CanaryBuildWarning: "Veuillez noter que vous utilisez une version nouvellement compilée qui n'a pas été soigneusement testée. Ce mode est donc plus susceptible de contenir des bugs cassant le jeu ou votre sauvegarde, et il est strictement réservé aux tests de jeu. NE PAS utiliser cette version pour le jeu normal."
};