export default {
  TrafficSignal: "Verkeerslicht",
  ModDefault: "Default",
  Vanilla: "Standaard",
  SplitPhasing: "Gescheiden fasering",
  AdvancedSplitPhasing: "Geavanceerde gescheiden fasering",
  ProtectedRightTurns: "Beschermde bochten naar rechts",
  ProtectedLeftTurns: "Beschermde bochten naar links",
  Options: "Opties",
  ExclusivePedestrianPhase: "Exclusieve voetgangers fase",
  AlwaysGreenLeftTurns: "Altijd groen links-afslaand verkeer",
  AlwaysGreenRightTurns: "Altijd groen rechts-afslaand verkeer",
  LaneDirectionTool: "Voorsorteren (Experimenteel)",
  Close: "Sluiten",
  Open: "Openen",
  Reset: "Herstellen",
  Save: "Opslaan",
  PleaseSave: "Sla de wijzigingen op voordat u een andere kruising selecteert.",
  PleaseSelectJunction: "Selecteer een kruising",
  Left: "Links",
  Ahead: "Rechtdoor",
  Right: "Rechts",
  UTurn: "U-bocht",
  GiveWayToOncomingVehicles: "Geef voorrang aan naderende voertuigen",
  CustomPedestrianDurationMultiplier: "Duur van de voetgangersfase",
  CustomPedestrianDurationMultiplierSuffix: "x",
  AllowTurningOnRed: "Toestaan ​​om rechtsaf te slaan bij rood licht",
  CanaryBuildWarning: "Houd er rekening mee dat je een testversie gebruikt, die waarschijnlijk ernstige fouten kan bevatten die het spel of je voortgang kunnen verstoren. Gebruik deze versie NIET voor normale spellen."
};