export default {
  TrafficSignal: "Sygnalizacja świetlna",
  ModDefault: "Default",
  Vanilla: "Domyślna",
  SplitPhasing: "Podział faz",
  AdvancedSplitPhasing: "Zaawansowany Podział faz",
  ProtectedRightTurns: "Chroniony prawoskręt",
  ProtectedLeftTurns: "Chroniony lewoskręt",
  Options: "Opcje",
  ExclusivePedestrianPhase: "Dedykowana faza dla pieszych",
  AlwaysGreenLeftTurns: "Zawsze dozwolone lewoskręty",
  AlwaysGreenRightTurns: "Zawsze dozwolone prawoskręty",
  LaneDirectionTool: "Narzędzie zmiany strzałek pasów (Eksperymentalne)",
  Close: "Zamknij",
  Open: "Otwórz",
  Reset: "Reset",
  Save: "Zapisz",
  PleaseSave: "Proszę zapisać zmiany przed wybraniem innego skrzyżowania.",
  PleaseSelectJunction: "Wybierz skrzyżowanie",
  Left: "Lewo",
  Ahead: "Prosto",
  Right: "Prawo",
  UTurn: "Zawracanie",
  GiveWayToOncomingVehicles: "Ustąp pierwszeństwa pojazdom z naprzeciwka",
  CustomPedestrianDurationMultiplier: "Czas trwania fazy dla pieszych",
  CustomPedestrianDurationMultiplierSuffix: "x",
  AllowTurningOnRed: "Pozwalaj na skręcanie na czerwonym",
  CanaryBuildWarning: "Pamiętaj, że używasz wersji canary, która może zawiera błędy psujące grę lub powodujące uszkodzenie zapisu i jest przeznaczona wyłącznie do testowania gry. NIE używaj tej wersji do normalnej rozgrywki."
};