export default {
  TrafficSignal: "Светофор",
  ModDefault: "Default",
  Vanilla: "По умолчанию",
  SplitPhasing: "Очередь",
  AdvancedSplitPhasing: "Продвинутая очередь",
  ProtectedRightTurns: "Защищенные правые повороты",
  ProtectedLeftTurns: "Защищенные левые повороты",
  Options: "Настройки",
  ExclusivePedestrianPhase: "Отдельная фаза для пешеходов",
  AlwaysGreenLeftTurns: "Всегда «зеленый» на левый поворот",
  AlwaysGreenRightTurns: "Всегда «зеленый» на правый поворот",
  LaneDirectionTool: "Настройка направления полос (экспериментально)",
  Close: "Закрыть",
  Open: "Открыть",
  Reset: "Сбросить",
  Save: "Сохранить",
  PleaseSave: "Пожалуйста, сохраните изменения, прежде чем выбирать другой перекресток",
  PleaseSelectJunction: "Пожалуйста, выберите перекресток",
  Left: "Налево",
  Ahead: "Прямо",
  Right: "Направо",
  UTurn: "Разворот",
  GiveWayToOncomingVehicles: "Уступить дорогу встречному транспорту",
  CustomPedestrianDurationMultiplier: "Продолжительность фазы для пешеходов",
  CustomPedestrianDurationMultiplierSuffix: "⨯",
  AllowTurningOnRed: "Разрешить поворот на красный свет",
  CanaryBuildWarning: "Обратите внимание, что вы используете тестовую сборку, которая может содержать ошибки, нарушающие игровой процесс или может повредить сохранение, и предназначена исключительно для тестирования. НЕ используйте эту сборку для обычной игры.",
  LdtMigrationNotice: "Lane Direction Tool has now been retired and succeeded by Traffic mod from krzychu124. Please install the Traffic mod, and it will automatically transfer your current lane settings to it. Click for more details (Open in a web browser).",
  LdtRetirementNotice: "Lane Direction Tool has now been retired and succeeded by Traffic mod from krzychu124. Thank you for using LDT."
};